# Generated by Django 3.1.3 on 2022-12-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20221222_0753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='choices',
            new_name='choice',
        ),
    ]
